server {
    listen 4200;
    root /usr/share/nginx/html;
    index index.html;

    # Seguridad — headers en todas las respuestas
    add_header X-Content-Type-Options  "nosniff"       always;
    add_header X-Frame-Options         "DENY"          always;
    add_header X-XSS-Protection        "1; mode=block" always;
    add_header Content-Security-Policy
        "default-src 'self'; \
         script-src 'self' 'unsafe-inline'; \
         style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; \
         font-src 'self' https://fonts.gstatic.com; \
         img-src 'self' data: http://localhost:3000; \
         connect-src 'self' http://localhost:3001 http://localhost:3000 http://localhost:5233; \
         frame-ancestors 'none';"
        always;

    # SPA — todas las rutas van al index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
