name: Docker - contenido-api

on:
  push:
    branches:
      - features/docker-workflows
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    uses: ./.github/workflows/docker-reusable.yml
    with:
      service-name: contenido-api
      dockerfile-path: ./contenido-api/Dockerfile
      context-path: ./contenido-api
      image-name: contenido-api
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
